[profile.default]
#evm_version = "constantinople"
optimizer = true
optimizer_runs = 200
remappings = ["cross=lib/diode"]

[profile.lint]
# Note: To exclude test/forge-std/**, run: forge lint contracts test/*.sol

 
